# Generated by Django 3.2.6 on 2021-09-01 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='date_added',
        ),
    ]
